use healthcare_db;

## Create a Table having columns same as the csv file to import 
create table patients(
	age int,
    gender varchar(50),
    medical_condition varchar(50), 
    date_of_admission date,
	doctor varchar(50), 
    hospital varchar(150),
    insurance_provider varchar(50), 
    billing_amount decimal(10,2), 
    admission_type varchar(50), 
    discharge_date date, 
    medication varchar(50),
    age_group varchar(50), 
    patient_id int, 
    length_of_stays int    
);


select *from patients;

##IMPORT THE CLEANED CSV FILE INTO THE DATABASE
set global local_infile= 1;

load data local infile 'C:\\Users\\Lenovo\\Desktop\\data analytics projects\\Healthcare Analysis\\cleaned_dataset.csv'
into table patients
fields terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 rows;

#1 WRITE A QUERY TO FIND TOTAL NUMBERS OF MALE & FEMALE PATIENTS IN DATABASE

select gender,count(*) as total_patients
from patients
group by gender;

#2 WHICH INSURANCE PROVIDER HAS THE HIGHEST NUMBER OF PATIENTS ASSOCIATED WITH IT

select insurance_provider,count(*) as total_patients
from patients
group by insurance_provider
order by total_patients desc
limit 1;

#3 LIST THE TOP 10 PATIENTS NAME AND PATIENT ID WHO HAD HIGHEST BILLING AMOUNT

select patient_id,gender,billing_amount
from patients
order by billing_amount desc
limit 10;

#4 FIND THE MOST COMMON MEDICAL CONDITION FOR PATIENTS IN THE SENIOR AGE GROUP

select medical_condition,count(*) as total_cases
from patients
where age_group = 'Senior'
group by medical_condition
order by total_cases desc
limit 1;

#5 CALCULATE THE AVERAGE LENGTH OF STAYS FOR EACH MEDICAL CONDITION SORT RESULTS FROM LONGEST STAY TO SHORTEST

select medical_condition,round(avg(length_of_stays),1) as avg_stay
from patients
group by medical_condition
order by avg_stay desc;

#6 FIND THE TOP 5 DOCTORS WHO HAVE TREATED THE MOST PATIENTS DISPLAY THEIR NAMES AND TOTAL COUNT OF PATIENTS

select doctor,count(*) as most_patient
from patients
group by doctor
order by most_patient desc
limit 5;

#7 LIST ALL UNIQUE MEDICATIONS PRESCRIBED FOR THE MEDICAL CONDITION 'DIABETES' 

select distinct medication 
from patients
where medical_condition='Diabetes';

#8 CALCULATE THE TOTAL BILLING AMOUNT GENERATED BY EACH HOSPITAL BUT ONLY FOR EMERGENCY ADMISSION TYPE

select distinct hospital,sum(billing_amount) as total_billamount
from patients
where admission_type='Emergency'
group by hospital
order by total_billamount desc;

#9 IDENTIFY ANY PATIENT ID THAT APPEARS MORE THAN ONCE IN THE TABLE SHOW PATIENTS ID AND HOW MANY TIMES THEY WERE ADMITTED

select patient_id,count(*) as total_admitted_time
from patients
group by patient_id
having total_admitted_time > 1
order by total_admitted_time desc;

#10 FIND THE DOCTOR WHO HAS LOWEST AVERAGE LENGTH OF STAYS OF LESS THAN 7 DAYS 

select doctor,round(avg(length_of_stays),1) as avg_stay,
round(avg(billing_amount),2) as avg_bill
from patients
group by doctor
having avg_stay < 7 
order by avg_bill asc
limit 5;